/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_framework_nativeapp_NativeCode */

#ifndef _Included_by_framework_nativeapp_NativeCode
#define _Included_by_framework_nativeapp_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_framework_nativeapp_NativeCode
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_framework_nativeapp_NativeCode_getInt
  (JNIEnv *, jobject);

/*
 * Class:     by_framework_nativeapp_NativeCode
 * Method:    showInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_by_framework_nativeapp_NativeCode_showInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     by_framework_nativeapp_NativeCode
 * Method:    showIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_by_framework_nativeapp_NativeCode_showIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     by_framework_nativeapp_NativeCode
 * Method:    getRandomInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_framework_nativeapp_NativeCode_getRandomInt
  (JNIEnv *, jobject);

/*
 * Class:     by_framework_nativeapp_NativeCode
 * Method:    addOneToArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_by_framework_nativeapp_NativeCode_addOneToArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     by_framework_nativeapp_NativeCode
 * Method:    srand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_framework_nativeapp_NativeCode_srand
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
